### PR TITLE
Fixing unbalanced speaker page layout

### PR DESCRIPTION
**Pull request by ttraenkler**
- I've fixed the collapsing layout of the speaker page when there is no abstract to deal with missing content
- rounded off a few rough edges, in particular on smaller tablets in portrait mode the layout switched to column mode more quickly #62. 
- Also, on mobile the layout was confusing, if you click on the card you see the card again with no headline, therefore I moved the card down and added a headline. 
- aspect ratio of the speaker card now matches the speakers page
- layout starts on the top of the screen instead of in the middle to lessen the orphaned look when there is little content

here how it was before

Bildschirmfoto 2020-01-14 um 13 12 15

and after:
Bildschirmfoto 2020-01-14 um 13 13 02

### CODE REVIEW

**Comment by ttraenkler** [comment]
This fixes the confusing and empty looking speaker page layout

Bildschirmfoto 2020-01-14 um 13 04 49
Bildschirmfoto 2020-01-14 um 13 04 26

**Comment by ttraenkler** [comment]
I would recommend to merge this before announcing, since it fixes some weird looking layout glitches on the speaker page especially for those with no content or on large screens or mobile.

**Comment by ttraenkler** [comment]
Since we did not have a consensus on this I am asking for more opinions. 
@ashleygwilliams  @surma @natorion @torch2424

**Comment by ttraenkler** [comment]
This PR fixes a couple of glitches. If the only concern is the title on the speaker card. I will remove it from the PR even if it looks weird to me.

**Comment by ttraenkler** [comment]
@ashleygwilliams I've removed the title from the card

**Comment by ttraenkler** [comment]
with regard to the title, the intention was not to make the page look more full but to match the design of the speakers page and make the card look like a badge. nevertheless this is no longer part of this PR

**Comment by ashleygwilliams** [comment]
marking as blocked. i would like to wait until announcements are done to review further changes to these pages. in the meantime, updated screencaps would be helpful for review. thanks!

**Comment by ttraenkler** [comment]
Card talk title had been removed as requested and other changes specified. Screenshots are otherwise up to date except the title on the card being removed. I suggest we close it since it was meant to be merged before announcing.

**Comment by ttraenkler** [comment]
I will break up this PR, that was intended as a hotfix before the announcement, into smaller PRs only addressing one layout issue at a time to make the reviewers task easier and make finding a consensus easier. This week I am short on time so instead of the PRs I leave this comment.

**Pull request closed without merging**
