### PR TITLE
Created a Schedule Page, and added the current running order

### PR DESCRIPTION
**Pull request by torch2424**
Hello!

As requested, I made a schedule page for the website, with an okay looking design :smile: 

Mostly inspired by last years, and I think once we have the times nailed down, we can iterate the design and I think it'll look awesome :smile: 

Also, I added a `<p>` tag for the abstracts once we get all the info from speakers :smile: And I also added a quick README hotfix, hope you don't mind! :smile: 

# Screenshots

localhost_5000_schedule(iPhone 6_7_8)
Screenshot from 2021-01-28 15-43-28

### CODE REVIEW

**Comment by surma** [comment]
@torch2424 I added one commit to float the speaker images. Let me know what you think!

**Comment by torch2424** [comment]
@surma I think it looks great! :smile: :tada:

**Comment by torch2424** [comment]
@surma This PR should now be good to go, and ready for the speaker announcements! :smile: :pray:

**Comment by torch2424** [comment]
Oh wait, just got an email back from BBC, now we are good to go (I added their logo and abstract per their permission :smile: )

Screenshot from 2021-02-17 13-53-28

**Review by surma — APPROVED** [review]

**Pull request merged**
