### PR TITLE
added service worker for offline support

### PR DESCRIPTION
**Pull request by ttraenkler**
- added next.js offline support #41 following tutorials on:
  -  https://nextjs.org/features/progressive-web-apps#offline-support and
  - https://github.com/hanford/next-offline#usage
- this is experimental and not tested 
- to test it we need to deploy and use https

### CODE REVIEW

**Comment by torch2424** [comment]
I can test this! I have a [SSH Reverse Tunnel](https://www.howtogeek.com/428413/what-is-reverse-ssh-tunneling-and-how-to-use-it/) set up, so I can test this under https 😄

**Comment by torch2424** [comment]
I got this error when trying to build 😯 : 

Screen Shot 2020-01-08 at 9 29 33 PM

**Comment by ttraenkler** [comment]
@torch2424 Thanks for the note, solved in #59. In the meanwhile until this gets merged into dev, I applied the patch to this branch so you should be able to continue.

**Comment by ashleygwilliams** [comment]
now that #59 is merged let's have @torch2424 test again!

**Comment by torch2424** [comment]
@ashleygwilliams @ttraenkler 

Thanks for the fixes! So I got it to build and all that:

Screen Shot 2020-01-09 at 11 10 33 AM

But as you can see in the console, the service worker failed due to a 404? Unless `npm run start` does not serve the service worker? 🤔 And the network tab does show that it 404's when trying to fetch the service worker:

Screen Shot 2020-01-09 at 11 12 45 AM

**Comment by ttraenkler** [comment]
@torch2424 I've made https://webassembly.eu a PWA with offline support and after confirming that it worked applied the same patches here.

Below the screenshot of the standalone WebAssembly EU PWA on MacOS:

Bildschirmfoto 2020-01-10 um 19 18 55

**Comment by torch2424** [comment]
So I went ahead and tried both:

`npm run build`, and then `npm run start`. Which didn't work, same error :(

Then I tried [next export](https://nextjs.org/learn/excel/static-html-export/export-the-index-page), and I got farther along! But it seems like the icon that was chosen isn't valid for the `manifest.json`?

Screen Shot 2020-01-10 at 11 12 58 AM
Screen Shot 2020-01-10 at 11 12 45 AM

**Pull request merged**
